export const lightingDesignGalleries: Record<string, string[]> = {
  "silent-night-of-the-lambs": [
    "/images/lighting-design/silent-night-of-the-lambs/SNOTL107.jpg",
    "/images/lighting-design/silent-night-of-the-lambs/SNOTL132.jpg",
    "/images/lighting-design/silent-night-of-the-lambs/SNOTL110.jpg",
    "/images/lighting-design/silent-night-of-the-lambs/SNOTL159.jpg",
    "/images/lighting-design/silent-night-of-the-lambs/SNOTL120.jpg",
    "/images/lighting-design/silent-night-of-the-lambs/SNOTL129.jpg",
    "/images/lighting-design/silent-night-of-the-lambs/SNOTL144.jpg",
  ],
  "something-rotten": [
    "/images/lighting-design/something-rotten/080124+-+UCLA+MTSI+-+SOMETHING+ROTTEN+-+FH3-1.JPG",
    "/images/lighting-design/something-rotten/080124+-+UCLA+MTSI+-+SOMETHING+ROTTEN+-+FH3-18.JPG",
    "/images/lighting-design/something-rotten/080124+-+UCLA+MTSI+-+SOMETHING+ROTTEN+-+FH3-10.JPG",
    "/images/lighting-design/something-rotten/080124+-+UCLA+MTSI+-+SOMETHING+ROTTEN+-+FH3-15.JPG",
    "/images/lighting-design/something-rotten/080124+-+UCLA+MTSI+-+SOMETHING+ROTTEN+-+FH3-11.JPG",
    "/images/lighting-design/something-rotten/080124+-+UCLA+MTSI+-+SOMETHING+ROTTEN+-+FH3-21.JPG",
    "/images/lighting-design/something-rotten/080124+-+UCLA+MTSI+-+SOMETHING+ROTTEN+-+FH3-3.JPG",
  ],
  "the-nerd": [
    "/images/lighting-design/the-nerd/Alley+Theatre+-+The+Nerd+-+Final+Dress+-+Photographer+Lynn+Lane-1.jpg",
    "/images/lighting-design/the-nerd/Alley+Theatre+-+The+Nerd+-+Final+Dress+-+Photographer+Lynn+Lane-2.jpg",
    "/images/lighting-design/the-nerd/Alley+Theatre+-+The+Nerd+-+Final+Dress+-+Photographer+Lynn+Lane-3.jpg",
    "/images/lighting-design/the-nerd/Alley+Theatre+-+The+Nerd+-+Final+Dress+-+Photographer+Lynn+Lane-4.jpg",
  ],
  "a-christmas-carol": [
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-15.JPG",
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-8.JPG",
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-3.JPG",
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-1.JPG",
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-2.JPG",
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-5.JPG",
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-7.JPG",
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-6.JPG",
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-11.JPG",
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-12.JPG",
    "/images/lighting-design/a-christmas-carol/11182023+-+Alley+-+CAROL+-+FH3-10.JPG",
  ],
  "little-comedies": [
    "/images/lighting-design/little-comedies/Alley_Theatre_Little_Comedies_Photographer_Lynn_Lane-69-scaled.jpg",
    "/images/lighting-design/little-comedies/Alley_Theatre_Little_Comedies_Photographer_Lynn_Lane-118-scaled.jpg",
    "/images/lighting-design/little-comedies/Alley_Theatre_Little_Comedies_Photographer_Lynn_Lane-246-scaled.jpg",
    "/images/lighting-design/little-comedies/Alley_Theatre_Little_Comedies_Photographer_Lynn_Lane-312-scaled.jpg",
    "/images/lighting-design/little-comedies/Alley_Theatre_Little_Comedies_Photographer_Lynn_Lane-346-scaled.jpg",
  ],
  "american-mariachi": [
    "/images/lighting-design/american-mariachi/AM_ALLEY_11.jpg",
    "/images/lighting-design/american-mariachi/AM_ALLEY_1.jpg",
    "/images/lighting-design/american-mariachi/AM_ALLEY_2.jpg",
    "/images/lighting-design/american-mariachi/AM_ALLEY_3.jpg",
    "/images/lighting-design/american-mariachi/AM_ALLEY_4.jpg",
    "/images/lighting-design/american-mariachi/AM_ALLEY_5.jpg",
    "/images/lighting-design/american-mariachi/AM_ALLEY_6.jpg",
    "/images/lighting-design/american-mariachi/AM_ALLEY_8.jpg",
    "/images/lighting-design/american-mariachi/AM_ALLEY_9.jpg",
    "/images/lighting-design/american-mariachi/AM_ALLEY_10.jpg",
    "/images/lighting-design/american-mariachi/AM_ALLEY_12.jpg",
    "/images/lighting-design/american-mariachi/Alley-Theatre-American-Mariachi-Photographer-Lynn-Lane-366-scaled.jpg",
  ],
  "the-play-that-goes-wrong": [
    "/images/lighting-design/the-play-that-goes-wrong/05022023-LNK_TPTGW-FH3-6.JPG",
    "/images/lighting-design/the-play-that-goes-wrong/05022023-LNK_TPTGW-FH3-12.JPG",
    "/images/lighting-design/the-play-that-goes-wrong/05022023-LNK_TPTGW-FH3-61.JPG",
    "/images/lighting-design/the-play-that-goes-wrong/05022023-LNK_TPTGW-FH3-63.JPG",
    "/images/lighting-design/the-play-that-goes-wrong/05022023-LNK_TPTGW-FH3-66.JPG",
  ],
  "eugene-onegin": [
    "/images/lighting-design/eugene-onegin/Onegin+1.jpg",
    "/images/lighting-design/eugene-onegin/2022-04-18+Onegin+1077-02869.jpg",
    "/images/lighting-design/eugene-onegin/Onegin+3.jpg",
    "/images/lighting-design/eugene-onegin/Onegin+4.jpg",
    "/images/lighting-design/eugene-onegin/TGradyPhoto-01670.jpg",
    "/images/lighting-design/eugene-onegin/TGradyPhoto-03219.jpg",
  ],
  "evening-of-dance-2021": [
    "/images/lighting-design/evening-of-dance-2021/IMG_8890.JPG",
    "/images/lighting-design/evening-of-dance-2021/2021_04_26+-+Dance+Rehearsal-88.jpg",
    "/images/lighting-design/evening-of-dance-2021/IMG_8891.JPG",
    "/images/lighting-design/evening-of-dance-2021/IMG_8892.JPG",
    "/images/lighting-design/evening-of-dance-2021/IMG_8894.JPG",
  ],
  "holiday-inn": [
    "/images/lighting-design/holiday-inn/FH3-11302022-HOLIDAY+INN-14.jpg",
    "/images/lighting-design/holiday-inn/FH3-11302022-HOLIDAY+INN-11.jpg",
    "/images/lighting-design/holiday-inn/FH3-11302022-HOLIDAY+INN-19.jpg",
    "/images/lighting-design/holiday-inn/FH3-11302022-HOLIDAY+INN-16.jpg",
    "/images/lighting-design/holiday-inn/FH3-11302022-HOLIDAY+INN-18.jpg",
    "/images/lighting-design/holiday-inn/FH3-11302022-HOLIDAY+INN-13.jpg",
    "/images/lighting-design/holiday-inn/FH3-11302022-HOLIDAY+INN-20.jpg",
    "/images/lighting-design/holiday-inn/FH3-11302022-HOLIDAY+INN-12.jpg",
    "/images/lighting-design/holiday-inn/FH3-11302022-HOLIDAY+INN-15.jpg",
  ],
  "our-town": [
    "/images/lighting-design/our-town/FH3-OT-01.jpeg",
    "/images/lighting-design/our-town/FH3_3460.jpg",
    "/images/lighting-design/our-town/FH3-OT-22.jpeg",
    "/images/lighting-design/our-town/FH3-OT-38.jpeg",
    "/images/lighting-design/our-town/FH3-OT-26.jpeg",
    "/images/lighting-design/our-town/FH3-OT-13.jpeg",
    "/images/lighting-design/our-town/FH3_4700.jpg",
    "/images/lighting-design/our-town/FH3_4626.jpg",
    "/images/lighting-design/our-town/FH3_3445.jpg",
    "/images/lighting-design/our-town/FH3_4595.jpg",
  ],
  "shakesfear": [
    "/images/lighting-design/shakesfear/FH3-10122022-SHAKESFEAR-MH-18.jpg",
    "/images/lighting-design/shakesfear/FH3-10122022-SHAKESFEAR-MH-34.jpg",
    "/images/lighting-design/shakesfear/FH3-10122022-SHAKESFEAR-MH-16.jpg",
    "/images/lighting-design/shakesfear/FH3-10122022-SHAKESFEAR-MH-19.jpg",
    "/images/lighting-design/shakesfear/FH3-10122022-SHAKESFEAR-MH-40.jpg",
    "/images/lighting-design/shakesfear/FH3-10122022-SHAKESFEAR-MH-47.jpg",
    "/images/lighting-design/shakesfear/FH3-10122022-SHAKESFEAR-MH-32.jpg",
  ],
  "student-dance-projects": [
    "/images/lighting-design/student-dance-projects/IMG_0313.JPG",
    "/images/lighting-design/student-dance-projects/IMG_0308.JPG",
    "/images/lighting-design/student-dance-projects/IMG_0281.JPG",
    "/images/lighting-design/student-dance-projects/IMG_0216.JPG",
    "/images/lighting-design/student-dance-projects/IMG_0250.JPG",
  ],
  "the-marriage-of-figaro": [
    "/images/lighting-design/the-marriage-of-figaro/FH3-11102022-FIGARO-42.jpg",
    "/images/lighting-design/the-marriage-of-figaro/FH3-11102022-FIGARO-1.jpg",
    "/images/lighting-design/the-marriage-of-figaro/FH3-11102022-FIGARO-3.jpg",
    "/images/lighting-design/the-marriage-of-figaro/FH3-11102022-FIGARO-45.jpg",
    "/images/lighting-design/the-marriage-of-figaro/FH3-11102022-FIGARO-41.jpg",
    "/images/lighting-design/the-marriage-of-figaro/FH3-11102022-FIGARO-37.jpg",
  ],
  "tmfd-department-installation": [
    "/images/lighting-design/tmfd-department-installation/20210308_213323775_iOS.jpg",
    "/images/lighting-design/tmfd-department-installation/20210308_213300325_iOS.jpg",
    "/images/lighting-design/tmfd-department-installation/20210308_213309970_iOS.jpg",
    "/images/lighting-design/tmfd-department-installation/20210308_213336610_iOS.jpg",
    "/images/lighting-design/tmfd-department-installation/20210308_213351027_iOS.jpg",
    "/images/lighting-design/tmfd-department-installation/20210308_213239944_iOS.jpg",
  ],
  "traveling-shoes": [
    "/images/lighting-design/traveling-shoes/TS-1.jpg",
    "/images/lighting-design/traveling-shoes/TS-2.jpg",
    "/images/lighting-design/traveling-shoes/TS-3.jpg",
    "/images/lighting-design/traveling-shoes/TS-4.jpg",
    "/images/lighting-design/traveling-shoes/TS-5.jpg",
    "/images/lighting-design/traveling-shoes/TS-6.jpg",
    "/images/lighting-design/traveling-shoes/TS-7.jpg",
  ],
};
