import { lightingDesignGalleries } from "@/lib/lightingDesignGalleries";

export interface Collaborator {
  role: string;
  name: string;
}

export interface Show {
  slug: string;
  title: string;
  role: string;
  venue: string;
  location: string;
  year: number;
  image?: string;
  gallery?: string[];
  note?: string;
  collaborators?: Collaborator[];
  productionNotes?: string;
}

export const shows: Show[] = [
  {
    slug: "silent-night-of-the-lambs",
    title: "Silent Night of the Lambs",
    role: "Lighting Designer",
    venue: "Bluebarn Theatre",
    location: "Omaha, NE",
    year: 2024,
    image: "/images/SNOTL129.jpg",
    gallery: lightingDesignGalleries["silent-night-of-the-lambs"],
    collaborators: [
      { role: "Director", name: "Susan Clement" },
      { role: "Choreography", name: "Carrie Nath" },
      { role: "Scenic Design", name: "Martin Marchitto" },
      { role: "Sound & Projection Design", name: "Bill Kirby" },
      { role: "Costume Design", name: "Denise Evrin" },
      { role: "Stage Manager", name: "Nic Jansen" },
    ],
    productionNotes: "The brief was essentially: make it feel like Christmas and a horror film at the same time, in a 99-seat black box. I built a high-contrast zone system with deep cool isolations and warm amber, and leaned into hard shadow as a tool rather than an accident. The naturalistic holiday warmth and the unnerving darkness had to coexist without canceling each other out. Reviews picked up on the tonal range, and the run sold out.",
  },
  {
    slug: "something-rotten",
    title: "Something Rotten",
    role: "Lighting Designer",
    venue: "UCLA TFT MT Summer Institute",
    location: "Los Angeles, CA",
    year: 2024,
    image: "/images/080124-UCLA-MTSI-SOMETHING-ROTTEN-FH3-10.JPG",
    gallery: lightingDesignGalleries["something-rotten"],
    collaborators: [
      { role: "Director", name: "Jeff Maynard" },
      { role: "Scenic Design", name: "Michael Sellers" },
      { role: "Asst. Lighting Design", name: "Gus Cohen" },
      { role: "Sound Design", name: "Austin Taylor" },
      { role: "Stage Manager", name: "Jesse Vacchiano" },
    ],
    productionNotes: "This one asked for full Broadway energy on a summer institute budget. The scenic designer had marquee bulbs built into the set, so I used those as my warm anchor and built the wash system outward from that logic so the light felt like it was coming from the world rather than dropped on top of it. High-chroma primaries, fast and bright, sized up to match the ensemble.",
  },
  {
    slug: "the-nerd",
    title: "The Nerd",
    role: "Assistant Lighting Designer",
    venue: "Alley Theatre",
    location: "Houston, TX",
    year: 2024,
    image: "/images/Alley-Theatre-The-Nerd-Lynn-Lane-1.jpg",
    gallery: lightingDesignGalleries["the-nerd"],
    collaborators: [
      { role: "Director", name: "Brandon Weinbrenner" },
      { role: "Scenic Design", name: "Tim Mackabee" },
      { role: "Costume Design", name: "Haydee Zelideth" },
      { role: "Lighting Design", name: "Aja M. Jackson" },
      { role: "Sound Design", name: "Jane Shaw" },
      { role: "Stage Manager", name: "Kristen Larson" },
    ],
    productionNotes: "My first full Alley credit. Aja M. Jackson's design was rigorously naturalistic — every motivated source had to earn its place, and the comedy lived or died in the timing of those practicals. I kept her focus documentation and magic sheet airtight so she could make fast, confident calls in tech without losing ground. Working in that framework taught me how much precision a naturalistic design actually requires underneath.",
  },
  {
    slug: "a-christmas-carol",
    title: "A Christmas Carol",
    role: "Assistant Lighting Designer",
    venue: "Alley Theatre",
    location: "Houston, TX",
    year: 2023,
    image: "/images/11182023-Alley-CAROL-FH3-15.JPG",
    gallery: lightingDesignGalleries["a-christmas-carol"],
    collaborators: [
      { role: "Director", name: "Rob Melrose" },
      { role: "Scenic Design", name: "Michael Locher" },
      { role: "Costume Design", name: "Raquel Barreto" },
      { role: "Lighting Design", name: "Cat Tate Starmer" },
      { role: "Sound Design", name: "Cliff Caruthers" },
      { role: "Music Direction", name: "John L. Cornelius II" },
      { role: "Stage Manager", name: "Rebecca RD Hamlin" },
    ],
    productionNotes: "Carol is one of the Alley's biggest productions — flying sequences, snow, ghost transformations, over a hundred cues — and the tech period is always compressed. I tracked focus and kept the magic sheet current through rapid revision, serving as the line between Cat Tate Starmer and the board op so the design didn't lose ground under schedule pressure. It taught me that organizational discipline isn't just support work — it's the thing that protects the design.",
  },
  {
    slug: "little-comedies",
    title: "Little Comedies",
    role: "Assistant Lighting Designer",
    venue: "Alley Theatre",
    location: "Houston, TX",
    year: 2023,
    image: "/images/Alley_Theatre_Little_Comedies_Photographer_Lynn_Lane-346-scaled.jpg",
    gallery: lightingDesignGalleries["little-comedies"],
    collaborators: [
      { role: "Director", name: "Richard Nelson" },
      { role: "Scenic Design", name: "Michael Locher" },
      { role: "Costume Design", name: "Susan Hilferty & Camilla Dely" },
      { role: "Lighting Design", name: "Jennifer Tipton" },
      { role: "Sound Design", name: "Scott Lehrer" },
      { role: "Stage Manager", name: "Kristen Larson" },
    ],
    productionNotes: "Getting to assist Jennifer Tipton was something I didn't take lightly. Her approach strips everything back to architectural logic — no effect for its own sake, no safety-net cue. I spent most of tech just watching how she worked: how she talked to the director, how she listened, how she committed to a position and then tested it. The lessons about restraint I took from that room are still a direct reference point for me.",
  },
  {
    slug: "american-mariachi",
    title: "American Mariachi",
    role: "Assistant Lighting Designer",
    venue: "Alley Theatre",
    location: "Houston, TX",
    year: 2023,
    image: "/images/AM_ALLEY_6.jpg",
    gallery: lightingDesignGalleries["american-mariachi"],
    collaborators: [
      { role: "Director", name: "KJ Sanchez" },
      { role: "Scenic Design", name: "Tanya Orellana" },
      { role: "Costume Design", name: "Christopher Vergara" },
      { role: "Lighting Design", name: "Carolina Ortiz Herrera" },
      { role: "Sound Design", name: "Lindsay Jones" },
      { role: "Music Director", name: "Jesse J. Sanchez" },
      { role: "Stage Manager", name: "Ryan Barett" },
    ],
    productionNotes: "Carolina Ortiz Herrera's design was rich and warm — color functioning as cultural identity rather than just mood. I tracked cues and focus notes through previews and coordinated with the projections team to keep registration clean against the lighting. Three years into my career, this was the first production room I'd been in where so many of the artists — the designer, the director, the cast — were Mexican-American. Working alongside that team was a reminder that the work hits differently when you see yourself in it.",
  },
  {
    slug: "the-play-that-goes-wrong",
    title: "The Play That Goes Wrong",
    role: "Lighting Designer",
    venue: "Nebraska Repertory Theatre",
    location: "Lincoln, NE",
    year: 2023,
    image: "/images/05022023-LNK_TPTGW-FH3-66.JPG",
    gallery: lightingDesignGalleries["the-play-that-goes-wrong"],
    collaborators: [
      { role: "Director", name: "Ann Marie Pollard" },
      { role: "Scenic Design", name: "JD Madsen" },
      { role: "Sound Design", name: "Bryce Dale Allen" },
      { role: "Costume Design", name: "Camille Lerner" },
      { role: "Stage Manager", name: "Brad Buffum" },
    ],
    productionNotes: "The design had to do two things at once: read as a credible 1920s period play, and then systematically fall apart without the lighting just giving up on itself. I built a warm naturalistic proscenium base that could hold its own as a real production, then let the design's own logic get used against it as the chaos escalated. The goal was to make the shifts feel inevitable rather than cued, so the audience was laughing at the lighting right along with everything else.",
  },
  {
    slug: "holiday-inn",
    title: "Holiday Inn",
    role: "Lighting Designer",
    venue: "Nebraska Wesleyan University",
    location: "Lincoln, NE",
    year: 2022,
    image: "/images/FH3-11302022-HOLIDAY-INN-18.jpg",
    gallery: lightingDesignGalleries["holiday-inn"],
    collaborators: [
      { role: "Director", name: "Anne McAlexander" },
      { role: "Scenic Design", name: "Kelly Vogel" },
      { role: "Costume Design", name: "Elizabeth Ennis" },
      { role: "Assoc. Lighting Design", name: "Caroline Nowak" },
    ],
    productionNotes: "Holiday Inn spans a full calendar year of seasons across a dozen locations, all in one facility. I anchored the color system in two temperatures — cool blues for exterior and winter scenes, warm ambers and golds for the inn's interiors — so seasonal transitions read cleanly without the scenery having to do all the work. It gave the production a clear visual arc through a dense book.",
  },
  {
    slug: "the-marriage-of-figaro",
    title: "The Marriage of Figaro",
    role: "Lighting Designer",
    venue: "UNL School of Music",
    location: "Lincoln, NE",
    year: 2022,
    image: "/images/FH3-11102022-FIGARO-41.jpg",
    gallery: lightingDesignGalleries["the-marriage-of-figaro"],
    note: "MFA Thesis Production",
    collaborators: [
      { role: "Director", name: "Dr. William Shomos" },
      { role: "Conductor", name: "Dr. Tyler White" },
      { role: "Scenic Design", name: "JD Madsen" },
      { role: "Costume Design", name: "Camille Lerner" },
      { role: "Stage Manager", name: "Amy Guevara" },
    ],
    productionNotes: "My MFA thesis production — four acts of Mozart on a thrust stage with a live orchestra. The thrust configuration meant limited overhead positions, so I prioritized motivated naturalistic light with selective specials and built the cue structure directly against the score so transitions felt like part of the music rather than interruptions. The thesis committee cited the lighting as a mature example of compositional discipline.",
  },
  {
    slug: "shakesfear",
    title: "Shakesfear",
    role: "Associate Lighting Designer",
    venue: "Nebraska Repertory Theatre",
    location: "Lincoln, NE",
    year: 2022,
    image: "/images/FH3-10122022-SHAKESFEAR-MH-16.jpg",
    gallery: lightingDesignGalleries["shakesfear"],
    collaborators: [
      { role: "Written & Directed by", name: "Andy Park" },
      { role: "Scenic Design", name: "JD Madsen" },
      { role: "Costume Design", name: "Jamie Bullins" },
      { role: "Lighting Design", name: "Michelle Harvey" },
      { role: "Sound Design", name: "Jeff O'Brien" },
    ],
    productionNotes: "Michelle Harvey's design ran through the entire building — audiences moved through discrete rooms, each its own horror environment. My job was keeping the system documentation clean so each zone could be reprogrammed independently and the design held through the run without needing operator intervention in every space. My first associate credit, and a solid introduction to managing a complex multi-zone programming structure.",
  },
  {
    slug: "eugene-onegin",
    title: "Eugene Onegin",
    role: "Assistant Lighting Designer",
    venue: "Opera Omaha",
    location: "Omaha, NE",
    year: 2022,
    image: "/images/IMG_2856.JPG",
    gallery: lightingDesignGalleries["eugene-onegin"],
    collaborators: [
      { role: "Director", name: "Rosetta Cucchi" },
      { role: "Conductor", name: "Maestro Steven White" },
      { role: "Scenic Design", name: "Julia Noulin-Merat" },
      { role: "Costume Design", name: "Neil Fortin" },
      { role: "Lighting Design", name: "Pablo Santiago" },
    ],
    productionNotes: "Pablo Santiago's design was stark and near-monochromatic — a very specific vision brought in from outside the building with limited advance time to implement it. I prepared the focus documentation, managed local crew relationships, and stayed in the room during tech to catch any drift before it affected the atmosphere. My first professional opera credit, and a quick education in the particular rhythms of opera tech with a live conductor.",
  },
  {
    slug: "our-town",
    title: "Our Town",
    role: "Assistant Lighting Designer",
    venue: "Nebraska Repertory Theatre",
    location: "Lincoln, NE",
    year: 2022,
    image: "/images/FH3-OT-01.JPG",
    gallery: lightingDesignGalleries["our-town"],
    collaborators: [
      { role: "Director", name: "Arthur Feinsod" },
      { role: "Scenic Design", name: "Taylor Walters-Riggsbee" },
      { role: "Lighting Design", name: "Michelle Harvey" },
      { role: "Sound Design", name: "Emily Callahan" },
      { role: "Music Direction", name: "Charlie Alterman" },
      { role: "Costume Design", name: "Camille Lerner" },
      { role: "Stage Manager", name: "Brad Buffum" },
    ],
    productionNotes: "In Our Town the light is the scenery — there's nothing else holding up the world of the play. I assisted Michelle Harvey in refining the zone structure to get maximum expressive range out of a minimal rig, tracking focus and cue revisions through a director with very specific emotional demands. The experience made it clear that restraint is its own kind of craft: what you leave out of the design is as deliberate as what you put in.",
  },
  {
    slug: "traveling-shoes",
    title: "Traveling Shoes",
    role: "Lighting Designer",
    venue: "NRT / St. Louis Black Rep",
    location: "Lincoln, NE",
    year: 2022,
    image: "/images/03252022-Traveling-Shoes-NRT-17.jpg",
    gallery: lightingDesignGalleries["traveling-shoes"],
    collaborators: [
      { role: "Director", name: "Ron Himes" },
      { role: "Scenic Design", name: "Brad LaMotte" },
      { role: "Costume Design", name: "Paige Moeller" },
      { role: "Sound Design", name: "Bryce Dale Allen" },
    ],
    productionNotes: "Traveling Shoes is a documentary play — civil rights testimonies, community history — staged in a black box with emblematic scenery rather than realistic. I used selective isolation and cool-to-warm contrast to track the emotional weight of individual moments against the ensemble, letting tonal shifts carry the transitions that scenery couldn't. The goal was to give the most intimate testimonies room to land without the design calling attention to itself.",
  },
  {
    slug: "evening-of-dance-2021",
    title: "Evening of Dance 2021",
    role: "Lighting Designer",
    venue: "Lied Center / Glenn Korff School of Music",
    location: "Lincoln, NE",
    year: 2021,
    image: "/images/IMG_8890.JPG",
    gallery: lightingDesignGalleries["evening-of-dance-2021"],
    productionNotes: "A full evening of concert dance on a large proscenium — multiple pieces, multiple choreographers, all needing their own visual identity while reading as one program. I built the rig around high-angle moving heads and used bold beam architectures as the primary scenic environment, with ground-level washes underneath for skin warmth. The lighting ended up functioning as the scenery for the whole evening.",
  },
  {
    slug: "tmfd-department-installation",
    title: "TMFD Department Installation",
    role: "Lighting Designer",
    venue: "UNL TMFD Department Gallery",
    location: "Lincoln, NE",
    year: 2021,
    image: "/images/20210308_213300325_iOS.jpg",
    gallery: lightingDesignGalleries["tmfd-department-installation"],
    productionNotes: "A first-year MFA collaboration — me, Abbey Lynn Smith, and Michael Demi Demaree designing together for the first time. We were lighting a fashion and textile student exhibition in a gallery space, so the work had to read both as wearable garment and sculptural artifact. I combined focused spots with a projected organic gobo to give each piece its own presence while creating a shared backdrop that tied the room together.",
  },
  {
    slug: "student-dance-projects",
    title: "Student Dance Projects",
    role: "Lighting Designer",
    venue: "Glenn Korff School of Music",
    location: "Lincoln, NE",
    year: 2021,
    image: "/images/IMG_0216.JPG",
    gallery: lightingDesignGalleries["student-dance-projects"],
    collaborators: [
      { role: "Choreography", name: "Hannah Friedt & Valerie Gust" },
    ],
    productionNotes: "COVID protocols, reduced resources, performers in masks — the constraints were real. With a minimal rig I worked through directional color rather than position changes to give each piece its own identity, keeping transitions fast and the programming clean. Each piece still landed with its own feel, and honestly the limitations pushed toward clarity in a way that felt generative.",
  },
];
