export interface Collaborator {
  role: string;
  name: string;
}

export interface Show {
  slug: string;
  title: string;
  role: string;
  venue: string;
  location: string;
  year: number;
  image?: string;
  note?: string;
  collaborators?: Collaborator[];
}

export const shows: Show[] = [
  {
    slug: "silent-night-of-the-lambs",
    title: "Silent Night of the Lambs",
    role: "Lighting Designer",
    venue: "Bluebarn Theatre",
    location: "Omaha, NE",
    year: 2024,
    image: "/images/SNOTL129.jpg",
    collaborators: [
      { role: "Director", name: "Susan Clement" },
      { role: "Choreography", name: "Carrie Nath" },
      { role: "Scenic Design", name: "Martin Marchitto" },
      { role: "Sound & Projection Design", name: "Bill Kirby" },
      { role: "Costume Design", name: "Denise Evrin" },
      { role: "Stage Manager", name: "Nic Jansen" },
    ],
  },
  {
    slug: "something-rotten",
    title: "Something Rotten",
    role: "Lighting Designer",
    venue: "UCLA TFT MT Summer Institute",
    location: "Los Angeles, CA",
    year: 2024,
    image: "/images/080124-UCLA-MTSI-SOMETHING-ROTTEN-FH3-10.JPG",
    collaborators: [
      { role: "Director", name: "Jeff Maynard" },
      { role: "Scenic Design", name: "Michael Sellers" },
      { role: "Asst. Lighting Design", name: "Gus Cohen" },
      { role: "Sound Design", name: "Austin Taylor" },
      { role: "Stage Manager", name: "Jesse Vacchiano" },
    ],
  },
  {
    slug: "the-nerd",
    title: "The Nerd",
    role: "Assistant Lighting Designer",
    venue: "Alley Theatre",
    location: "Houston, TX",
    year: 2024,
    image: "/images/Alley-Theatre-The-Nerd-Lynn-Lane-1.jpg",
    collaborators: [
      { role: "Director", name: "Brandon Weinbrenner" },
      { role: "Scenic Design", name: "Tim Mackabee" },
      { role: "Costume Design", name: "Haydee Zelideth" },
      { role: "Lighting Design", name: "Aja M. Jackson" },
      { role: "Sound Design", name: "Jane Shaw" },
      { role: "Stage Manager", name: "Kristen Larson" },
    ],
  },
  {
    slug: "a-christmas-carol",
    title: "A Christmas Carol",
    role: "Assistant Lighting Designer",
    venue: "Alley Theatre",
    location: "Houston, TX",
    year: 2023,
    image: "/images/11182023-Alley-CAROL-FH3-15.JPG",
    collaborators: [
      { role: "Director", name: "Rob Melrose" },
      { role: "Scenic Design", name: "Michael Locher" },
      { role: "Costume Design", name: "Raquel Barreto" },
      { role: "Lighting Design", name: "Cat Tate Starmer" },
      { role: "Sound Design", name: "Cliff Caruthers" },
      { role: "Music Direction", name: "John L. Cornelius II" },
      { role: "Stage Manager", name: "Rebecca RD Hamlin" },
    ],
  },
  {
    slug: "little-comedies",
    title: "Little Comedies",
    role: "Assistant Lighting Designer",
    venue: "Alley Theatre",
    location: "Houston, TX",
    year: 2023,
    image: "/images/Alley_Theatre_Little_Comedies_Photographer_Lynn_Lane-346-scaled.jpg",
    collaborators: [
      { role: "Director", name: "Richard Nelson" },
      { role: "Scenic Design", name: "Michael Locher" },
      { role: "Costume Design", name: "Susan Hilferty & Camilla Dely" },
      { role: "Lighting Design", name: "Jennifer Tipton" },
      { role: "Sound Design", name: "Scott Lehrer" },
      { role: "Stage Manager", name: "Kristen Larson" },
    ],
  },
  {
    slug: "american-mariachi",
    title: "American Mariachi",
    role: "Assistant Lighting Designer",
    venue: "Alley Theatre",
    location: "Houston, TX",
    year: 2023,
    image: "/images/AM_ALLEY_6.jpg",
    collaborators: [
      { role: "Director", name: "KJ Sanchez" },
      { role: "Scenic Design", name: "Tanya Orellana" },
      { role: "Costume Design", name: "Christopher Vergara" },
      { role: "Lighting Design", name: "Carolina Ortiz Herrera" },
      { role: "Sound Design", name: "Lindsay Jones" },
      { role: "Music Director", name: "Jesse J. Sanchez" },
      { role: "Stage Manager", name: "Ryan Barett" },
    ],
  },
  {
    slug: "the-play-that-goes-wrong",
    title: "The Play That Goes Wrong",
    role: "Lighting Designer",
    venue: "Nebraska Repertory Theatre",
    location: "Lincoln, NE",
    year: 2023,
    image: "/images/05022023-LNK_TPTGW-FH3-66.JPG",
    collaborators: [
      { role: "Director", name: "Ann Marie Pollard" },
      { role: "Scenic Design", name: "JD Madsen" },
      { role: "Sound Design", name: "Bryce Dale Allen" },
      { role: "Costume Design", name: "Camille Lerner" },
      { role: "Stage Manager", name: "Brad Buffum" },
    ],
  },
  {
    slug: "holiday-inn",
    title: "Holiday Inn",
    role: "Lighting Designer",
    venue: "Nebraska Wesleyan University",
    location: "Lincoln, NE",
    year: 2022,
    image: "/images/FH3-11302022-HOLIDAY-INN-18.jpg",
    collaborators: [
      { role: "Director", name: "Anne McAlexander" },
      { role: "Scenic Design", name: "Kelly Vogel" },
      { role: "Costume Design", name: "Elizabeth Ennis" },
      { role: "Assoc. Lighting Design", name: "Caroline Nowak" },
    ],
  },
  {
    slug: "the-marriage-of-figaro",
    title: "The Marriage of Figaro",
    role: "Lighting Designer",
    venue: "UNL School of Music",
    location: "Lincoln, NE",
    year: 2022,
    image: "/images/FH3-11102022-FIGARO-41.jpg",
    note: "MFA Thesis Production",
    collaborators: [
      { role: "Director", name: "Dr. William Shomos" },
      { role: "Conductor", name: "Dr. Tyler White" },
      { role: "Scenic Design", name: "JD Madsen" },
      { role: "Costume Design", name: "Camille Lerner" },
      { role: "Stage Manager", name: "Amy Guevara" },
    ],
  },
  {
    slug: "shakesfear",
    title: "Shakesfear",
    role: "Associate Lighting Designer",
    venue: "Nebraska Repertory Theatre",
    location: "Lincoln, NE",
    year: 2022,
    image: "/images/FH3-10122022-SHAKESFEAR-MH-16.jpg",
    collaborators: [
      { role: "Written & Directed by", name: "Andy Park" },
      { role: "Scenic Design", name: "JD Madsen" },
      { role: "Costume Design", name: "Jamie Bullins" },
      { role: "Lighting Design", name: "Michelle Harvey" },
      { role: "Sound Design", name: "Jeff O'Brien" },
    ],
  },
  {
    slug: "eugene-onegin",
    title: "Eugene Onegin",
    role: "Assistant Lighting Designer",
    venue: "Opera Omaha",
    location: "Omaha, NE",
    year: 2022,
    image: "/images/IMG_2856.JPG",
    collaborators: [
      { role: "Director", name: "Rosetta Cucchi" },
      { role: "Conductor", name: "Maestro Steven White" },
      { role: "Scenic Design", name: "Julia Noulin-Merat" },
      { role: "Costume Design", name: "Neil Fortin" },
      { role: "Lighting Design", name: "Pablo Santiago" },
    ],
  },
  {
    slug: "our-town",
    title: "Our Town",
    role: "Assistant Lighting Designer",
    venue: "Nebraska Repertory Theatre",
    location: "Lincoln, NE",
    year: 2022,
    image: "/images/FH3-OT-01.JPG",
    collaborators: [
      { role: "Director", name: "Arthur Feinsod" },
      { role: "Scenic Design", name: "Taylor Walters-Riggsbee" },
      { role: "Lighting Design", name: "Michelle Harvey" },
      { role: "Sound Design", name: "Emily Callahan" },
      { role: "Music Direction", name: "Charlie Alterman" },
      { role: "Costume Design", name: "Camille Lerner" },
      { role: "Stage Manager", name: "Brad Buffum" },
    ],
  },
  {
    slug: "traveling-shoes",
    title: "Traveling Shoes",
    role: "Lighting Designer",
    venue: "NRT / St. Louis Black Rep",
    location: "Lincoln, NE",
    year: 2022,
    image: "/images/03252022-Traveling-Shoes-NRT-17.jpg",
    collaborators: [
      { role: "Director", name: "Ron Himes" },
      { role: "Scenic Design", name: "Brad LaMotte" },
      { role: "Costume Design", name: "Paige Moeller" },
      { role: "Sound Design", name: "Bryce Dale Allen" },
    ],
  },
  {
    slug: "evening-of-dance-2021",
    title: "Evening of Dance 2021",
    role: "Lighting Designer",
    venue: "Lied Center / Glenn Korff School of Music",
    location: "Lincoln, NE",
    year: 2021,
    image: "/images/20210308_213300325_iOS.jpg",
  },
  {
    slug: "tmfd-department-installation",
    title: "TMFD Department Installation",
    role: "Lighting Designer",
    venue: "UNL TMFD Department Gallery",
    location: "Lincoln, NE",
    year: 2021,
    image: "/images/IMG_0216.JPG",
  },
  {
    slug: "student-dance-projects",
    title: "Student Dance Projects",
    role: "Lighting Designer",
    venue: "Glenn Korff School of Music",
    location: "Lincoln, NE",
    year: 2021,
    image: "/images/IMG_8890.JPG",
    collaborators: [
      { role: "Choreography", name: "Hannah Friedt & Valerie Gust" },
    ],
  },
];
